### ISSUE TITLE
Zuordnung von Behandlungsverfahren zu Abwasserbehandlungsanlagen

### ISSUE THREAD

**Issue by GerdGenuit** [stadt-bielefeld/auik#1]
Es wir eine Möglichkeit benötigt, eine oder mehrere Behandlungsverfahren zu einer Abwasserbehandlungsanlge zuzuordnen. Dies sollte möglichst in einem eigenen Panel geschehen, das analog zur ELKA Maske aufgebaut sein sollte.
![grafik](https://user-images.githubusercontent.com/37661725/45668308-8afb3f00-bb1c-11e8-8505-d19e0cc87b2b.png)

**Comment by BjoernSchilberg** [comment]
@awoestmann , magste erst einmal schauen, wie viel Zeit Du für die Bearbeitung brauchen würdest? Danach würde dann Gerd entscheiden, ob und wie dringend er hier die Umsetzung benötigt. Dank Dir.
