### ISSUE TITLE
Unterseite "Bedienung" der AUIK-Website ist leer

### ISSUE THREAD

**Issue by jdugge** [stadt-bielefeld/auik#10]
Unter https://stadt-bielefeld.github.io/auik/bedienung.html findet sich nur eine Menüzeile, aber leider kein Inhalt.

**Comment by Tilkiyim** [comment]
Derzeit wird ein Handbuch zur Bedienung des AUIKs erstellt. Ob dieses dann unter "Bedienung" abgelegt wird oder hier direkt ist  noch nicht final geklärt.

**Comment by Tilkiyim** [comment]
Das Handbuch ist nun unter [/doc](https://github.com/stadt-bielefeld/auik/tree/master/doc) zu finden. 

Ich schließe hiermit vorerst das Issue, sollte es erneut Fragen geben kann es gerne wieder geöffnet werden.
