### ISSUE TITLE
Drucken Sielhaut PDFs 

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#144]
Wir bräuchten eine Möglichkeit die PDF der Sielhautsteckbriefe alle auf einmal zu drucken. 
Gibt es da eventuell ne einfache Lösung für? Bzw ist das überhaupt möglich?

**Comment by awoestmann** [comment]
Ich verstehe die Beschreibung jetzt so, dass neben der Möglichkeit den Steckbrief für den aktuellen Sielhautpunkt zu generieren (Button "Drucken" im Sielhaut Modul) auch die Steckbriefe für alle vorhandenen Sielhautpunkte in der Datenbank auf einmal generiert und gedruckt werden sollen. Ist das soweit richtig?

Grundsätzlich ist es kein Problem mehrere PDFs auf einmal zu generieren und auch mit JasperReports zu drucken.
Wir müssten aber auf jeden Fall die vorhandenen Export-Funktionen anpassen, da diese für jedes generierte PDF den PDF-Betrachter des Systems öffnen. Das würde ich bei ggf. vielen Sielhautpunkten in der DB eher kritisch sehen.

Möglich wären wohl Änderungen in der Art:
* Einfügen eines Buttons um alle Steckbriefe zu drucken
* Ein Klick auf den Button erzeugt alle Steckbriefe ohne einen PDF Betrachter zu öffnen
* Nach dem Erzeugen der PDFs wird ein Fenster geöffnet in dem nochmal nachgefragt wird ob wirklich x Steckbriefe gedruckt werden sollen
* Nach der Bestätigung werden alle PDFs mit den aktuellen Druckereinstellungen gedruckt

**Comment by Tilkiyim** [comment]
Hallo Alex,

mit drucken meine ich nicht physisch ausdrucken, das soll eben vermieden werden. Es geht darum alle PDFs auf einmal zu erstellen und in einem Ordner abzulegen. Das kann gerne über das drücken eines Buttons geschehen. Ich fände es glaube ich ganz gut, wenn es der unter der Kategorie Sielhaut unter einem extra Modul liegt. „Steckbriefe drucken“ oder so.
Vielleicht kann  man, wenn es nicht zu viel Aufwand ist dort auch eine Liste mit allen Punkten machen, sodass man einzelne, mehrere oder eben dort erstellen kann. Es müsste dann auch geschaut werden, dass die automatisch überspeichert werden in dem Ordner, oder, dass man den Ordner halt auswählen muss, bevor es gespeichert wird.

Hier so ungefähr meine ich:   :D
***@***.***
Kannst ja vielleicht mal sagen was du denkst wie viel Zeit das so in Anspruch nehmen würde.

Hast du noch nen Überblick wie viel Kapazität noch da ist?

Liebe
Grüße
Lisa


Von: Alexander Wöstmann ***@***.***>
Gesendet: Dienstag, 22. November 2022 12:17
An: stadt-bielefeld/auik ***@***.***>
Cc: Fuchs, Lisa (360.33) ***@***.***>; Assign ***@***.***>
Betreff: Re: [stadt-bielefeld/auik] Drucken Sielhaut PDFs (Issue #144)


Ich verstehe die Beschreibung jetzt so, dass neben der Möglichkeit den Steckbrief für den aktuellen Sielhautpunkt zu generieren (Button "Drucken" im Sielhaut Modul) auch die Steckbriefe für alle vorhandenen Sielhautpunkte in der Datenbank auf einmal generiert und gedruckt werden sollen. Ist das soweit richtig?

Grundsätzlich ist es kein Problem mehrere PDFs auf einmal zu generieren und auch mit JasperReports zu drucken.
Wir müssten aber auf jeden Fall die vorhandenen Export-Funktionen anpassen, da diese für jedes generierte PDF den PDF-Betrachter des Systems öffnen. Das würde ich bei ggf. vielen Sielhautpunkten in der DB eher kritisch sehen.

Möglich wären wohl Änderungen in der Art:

  *   Einfügen eines Buttons um alle Steckbriefe zu drucken
  *   Ein Klick auf den Button erzeugt alle Steckbriefe ohne einen PDF Betrachter zu öffnen
  *   Nach dem Erzeugen der PDFs wird ein Fenster geöffnet in dem nochmal nachgefragt wird ob wirklich x Steckbriefe gedruckt werden sollen
  *   Nach der Bestätigung werden alle PDFs mit den aktuellen Druckereinstellungen gedruckt

**Comment by Tilkiyim** [comment]
Hier ist alles erledigt, daher schließe ich das Issue
