### ISSUE TITLE
Behebung Doppelspeicherung bei Chronologie

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#155]
Nach Speichern eines neuen Chronologieeintrages, wird  nach Verlassen des Tabs nach gefragt ob ungespeicherte Daten gespeichert werden sollen. Wird hier "Ja" gewählt ist der Chronologieeintrag doppelt gespeichert.

**Comment by awoestmann** [comment]
Mit Commit 27595c6 sollte das Problem mit den doppelten Einträgen nicht mehr auftreten.

**Comment by awoestmann** [comment]
Hier scheint der "CellEditor" nicht zurückgesetzt zu werden selbst wenn die Daten der darunter liegenden Tabelle verändert werden.
Mit 73c960e6904a7ef34bf5810c4168d08a03441335 sollten nicht gespeicherte Änderungen verworfen werden wenn ein neues Objekt geöffnet wird und das Problem damit nicht mehr auftreten.

**Comment by awoestmann** [comment]
Auch hier schienen Teile des Panels nicht korrekt zurückgesetzt zu werden wenn ein neues Objekt geöffnet wurde.

Mit 36acb83 sollte das Problem gelöst sein.

**Comment by Tilkiyim** [comment]
Perfect! :)

**Comment by Tilkiyim** [comment]
@awoestmann : 
Leider ist erneut eine Mehrfachspeicherung der Chronologie aufgetaucht. Allerdings scheint es nur bei den (Sielhaut)Messstellen noch fehlerhaft zu sein.

**Comment by awoestmann** [comment]
Mit c8cd5077ce5b7644471dbe355188ac44c35ef9d5 sollte das Problem mit der Doppelspeicherung auch bei den Sielhautmessstellen nicht mehr auftreten. Das Problem war hier, dass durch das BasisPanel ein Modulwechsel ausgelöst wurde der das Speichern aller Panels unterbrochen hat.
