### ISSUE TITLE
Verbesserungen ImportPanel

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#156]
Nach dem Laden einer Datei, sollen die Analysen nicht ausgewählt sein. 
Import dann nur nach Auswahl von den zu importierenden Analysen. Und auch nur die ausgewählten Analysen sollen importiert werden. 

Bei den Farben Orange und Rot wurde noch nachgefragt ob man hier eine deutlicheren Farbunterscheid machen könnte um diese schneller/leichter auseinander halten zu können.

**Comment by awoestmann** [comment]
Mit #158 sollte dieses Issue dann auch gelöst sein oder?

**Comment by Tilkiyim** [comment]
Ja, damit lösche ich das Issue! 👍🏼
