### ISSUE TITLE
Handbuch im Repository verwalten

### ISSUE THREAD

**Issue by BjoernSchilberg** [stadt-bielefeld/auik#17]
Moin @Tilkiyim,
Moin @GerdGenuit ,
wir wärs wenn Ihr das Handbuch im Repository verwaltet. Vllt. im Verzeichnis [/doc](https://github.com/stadt-bielefeld/auik/tree/master/doc). Was meint Ihr?

**Comment by Tilkiyim** [comment]
Habe das Handbuch als pdf unter  [/doc](https://github.com/stadt-bielefeld/auik/tree/master/doc) abgelegt. 
Damit ist das Issue erledigt und wird von mir geschlossen. :)
