### ISSUE TITLE
Abfragen Allgemein

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#181]
- [ ] Abfragemodule über Dropdownmenü anwählbar (bisher in properties-Datei festgelegt welche Abfragen bei SB benutzt werden können)
- [ ]	Ergebnistabellen als csv exportierbar (siehe Abfrage Anfallstelle)
- [ ]	Objekte aus Ergebnistabelle anwählbar (siehe Abfrage Anfallstelle)
- [ ]	Bei allen Suchkriterien soll es immer auch die Möglichkeit geben „Alle Kategorien bzw. Keine Spezifizierung“ einzustellen
- [ ]	Grundeinstellung immer ohne Spezifizierung des Suchkriteriums
- [ ] Standmäßig soll das Abfragemodul "E-Satzung" geladen werden.

**Comment by Tilkiyim** [comment]
Hab drüber geschaut, das ist mir bisher aufgefallen
- [ ] Sachbearbeiter soll standartmäßig leer sein
- [ ] statt Suchkriterium "Entwässerungsgebiet," Suchkriterium "Kläranlageneinzuggebiet" 
--> Heepen (1.01-1.05), Brake Ost (4.20-4-24), Brake West (4.00-4.19), AOL (5.28-5.31 und 7.32, 7.33.& 7.34), Sennestadt (8.35 & 8.36), Verl Sende (9.37)
- [ ] inaktive Objekte müssen raus
- [ ] Ergebnistabelle: Bei Standort soll die Standortadresse auftauchen inklusive Hausnummer. Bisher erschneint nur das Wort "Adresse"
- [ ] In den meisten Abfragen tauchen die gleichen Objekte mehrfach auf (distinct?)

**Comment by awoestmann** [comment]
>  Sachbearbeiter soll standartmäßig leer sein

Sollte mit 8cd19b304b7c88319521331cdf7664e40f47c82b umgestellt sein.

> inaktive Objekte müssen raus

Mit af8c79a1db32f790642a01dcc4d32033da3abf77 sollten inaktive Objekte nicht mehr in den Abfragen gezeigt werden wenn es keinen entsprechenden Filter in der Abfrage gibt.

> In den meisten Abfragen tauchen die gleichen Objekte mehrfach auf (distinct?)

Mit c1e15b4f3f57173cec1f1b60e043f50c2253db5e sollte die Abfragen wo möglich auf "SELECT DISTINCT" umgestellt sein.

> statt Suchkriterium "Entwässerungsgebiet," Suchkriterium "Kläranlageneinzuggebiet" [...]

Mit c667742 ist der Punkt für die BasisAbfrage umgesetzt. Soll die Änderung noch auf weitere Abfragemodule ausgeweitet werden?

**Comment by Tilkiyim** [comment]
Bisher sehe ich da keine Relevanz, kann sein, dass das beim Testen der Sachbearbeiter:innen noch mal Thema wird. Ich schließe jetzt erstmal das Issue.
