### ISSUE TITLE
Abfragemodul Anhang 49 

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#182]
- [ ] Fettabscheider nicht auflisten
- [ ] „Alle“ in Suchkriterium „SachbearbeiterIn“ mit aufnehmen

**Comment by awoestmann** [comment]
Mit 1c0a40a9f3e3be8f709d83e70e8e8623c885f78d sollten keine Fettabscheider mehr in der Ergebnisliste auftauchen.
Die Oberfläche erlaubt jetzt nach Sachbearbeitern zu filtern.

**Comment by Tilkiyim** [comment]
Ein paar Sachen sind mir noch aufgefallen die bearbeitet werden müssen
- gelöschte Objekte werden noch angezeigt - > die müssen noch raus
- inaktive Objekte werden angezeigt, auch wenn nicht die Auswahl "inaktiv" gesetzt wurde

**Comment by awoestmann** [comment]
Mit e9ecc694b052634e92f7e7dea685494c17188560 sollte die Abfrage jetzt entsprechend angepasst sein.

**Comment by Tilkiyim** [comment]
Top!
