### ISSUE TITLE
Abfragemodul Fettabscheider

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#184]
- [ ] Suchkriteriuem Sachbearbeiter
- [ ] inaktive Fettabscheider sollen nicht gelistet werden

**Comment by awoestmann** [comment]
Mit 0dbd9f3b6e04030cc159bb3d4bdc7bc31c7b1fde in der Fettabscheider Auswertung nach Sachbearbeiter gefiltert werden können. Das Ergebnis sollte dazu nur noch aktive Objekte enthalten.

**Comment by Tilkiyim** [comment]
Die Vorauswahl bei Sachbearbeiter sollte leer sein. Eine alphabetische Sortierung der SB wäre schön :)

**Comment by awoestmann** [comment]
Mit 2a8de6c404595e96c354dfb637d4d2aa94915010 sollte die Sachbearbeiter Box entsprechend angepasst sein

**Comment by Tilkiyim** [comment]
Wunderbar!
