### ISSUE TITLE
Abfragemodul Probepunkte

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#185]
- [ ] Suchkriterium Sachbearbeiter (aus Tab Probenahmepunkt)
- [ ] Suchkriterium Probepunktart als Dropdownmenü

**Comment by awoestmann** [comment]
Mit 80d7db8e2e6cadda26935a78d139a1924e614860 sollten die beiden Änderungen soweit umgesetzt sein.

**Comment by Tilkiyim** [comment]
Bei den Probepunktarten meinte ich die bereits vorgegeben Katergorien in der bestehenden Auswertung: ( Da habe ich mich  undeutlich ausgedrückt)
- E-Satzungspunkte
- UWB-Punkte
- Selbstüberwachungspunkte
- inaktive Probepunkte
- Probenehmereinsätze

**Comment by awoestmann** [comment]
Mit 9491839823cf1dc90d8c5167440495185a22d231 habe ich die Probepunktart-Box jetzt auf die genannten Kategorien umgestellt und die alten Buttons entfernt.
Das Filtern nach Sachbearbeitern habe ich ebenfalls entsprechend umgestellt.

**Comment by Tilkiyim** [comment]
Bei Probepunktart müsste noch die Auswahl "ohne Spezifikation" dazukommen.
Bei den Sachbearbeiter wäre eine alphabetische Sortierung noch ganz schön.

**Comment by awoestmann** [comment]
Mit 681553cb378bd7f3abf95fd6a32f0f4ac7df1689 sollten die beiden Punkte jetzt auch erledigt sein.

**Comment by Tilkiyim** [comment]
passt!
