### ISSUE TITLE
Neues Abfragemodul- BasisAbfrage

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#186]
Mehrere Auswahlebenen 
(Kombi aus Modul Alle Objektarten und Anfallstelle)
1.	Objektart
2.	Anhang (wenn Objektart = Anfallstelle)
3.	Anlagenart (wenn Anfallstelle = 99) 

Weitere Suchkriterien für Differenzierung (Über Dropdown)
•	SachbearbeiterIn (Option für Gruppenrolle 360.33)
•	Entwässerungsgebiete 
•	Priorität 1-4
•	Wiedervorlage abgelaufen/aktiv

Ergebnistabelle:
-	Betreibername
-	Standort
-	Entwässerungsgebiet3
-	SB
-	E-Satzungsüberwachung vorhanden (wenn aktiver Probenahmepunkt mit gleicher Standort)
-	Anhang
-	Anlagenart
-	Bemerkung aus ObjektTab
-	Bemerkungen aus AnhangTab
-	Wiedervorlage
-	Priorität

**Comment by awoestmann** [comment]
Mit 977a6efdb8fe9b897e1f08115114f9805360b7f9 sollten die genannten Änderungen soweit abgeschlossen sein. Das Modul habe ich als "BasisAbfrage" hinzugefügt, dementsprechend kann es über diesen Namen über die properties eingebunden werden.

**Comment by Tilkiyim** [comment]
Ich habe getestet und folgendes ist mir bis dato aufgefallen/muss noch angepasst werden:

- Die Sachbearbeitervorauswahl sollte leer sein
- wäre es möglich bei den Entwässerungsgebieten eine Mehrfachauswahl einzustellen? Oder mehr Sinn macht sogar die Kläranlageneinzugsgebiete zu nehmen: Heepen (1.01-1.05), Brake Ost (4.20-4-24), Brake West (4.00-4.19), AOL (5.28-5.31 und 7.32, 7.33.& 7.34), Sennestadt (8.35 & 8.36), Verl Sende (9.37)Heepen (1.01-1.05), Brake Ost (4.20-4-24), Brake West (4.00-4.19), AOL (5.28-5.31 und 7.32, 7.33.& 7.34), Sennestadt (8.35 & 8.36), Verl Sende (9.37)
- unter Standort steht nur das Wort "Adresse" nicht aber die  eigentliche Standortadresse
- Objekte werden teilweise doppelt/dreifach angezeigt (Distinct?)
- inaktive Objekte rausnehmen
- Für den Export fände ich es noch gut, wenn es dafür einen Button gibt.

**Comment by awoestmann** [comment]
> Die Sachbearbeitervorauswahl sollte leer sein

Sollte mit 44151971429c0a4f08bee91d3365587f1db69f37 erledigt sein

> Objekte werden teilweise doppelt/dreifach angezeigt (Distinct?)
> inaktive Objekte rausnehmen

Mit 6fd208259cff2b06742657588e5cd347904506c4 sollten beide Punkte erledigt sein

> Für den Export fände ich es noch gut, wenn es dafür einen Button gibt.

Grundsätzlich wäre das kein Problem, aber wäre dieser dann nicht doppelt vorhanden wenn mit #181 ein Exportbutton über die Abfrageauswahl reinkommt?

> wäre es möglich bei den Entwässerungsgebieten eine Mehrfachauswahl einzustellen? Oder mehr Sinn macht sogar die Kläranlageneinzugsgebiete zu nehmen: Heepen (1.01-1.05), Brake Ost (4.20-4-24), Brake West (4.00-4.19), AOL (5.28-5.31 und 7.32, 7.33.& 7.34), Sennestadt (8.35 & 8.36), Verl Sende (9.37)Heepen (1.01-1.05), Brake Ost (4.20-4-24), Brake West (4.00-4.19), AOL (5.28-5.31 und 7.32, 7.33.& 7.34), Sennestadt (8.35 & 8.36), Verl Sende (9.37)

Die zweite Variante wäre vermutlich die einfachere da Swing soweit ich weiß nicht sehr viel bietet um eine Mehrfachauswahl zu implementieren und wir da viel selbst bauen müssten. Für die zweite Variante könnte ich Elemente in der Combobox entsprechend ändern und die Abfrage anpassen, so dass die Id-Listen in den Klammern für die Filterung verwendet werden.


> unter Standort steht nur das Wort "Adresse" nicht aber die eigentliche Standortadresse

Das Problem konnte ich bisher nicht reproduzieren. Könntest du nochmal schreiben wie du das Objekt erstellst das mit dem Wort "Adresse" in der Liste auftaucht?

**Comment by Tilkiyim** [comment]
> > Die Sachbearbeitervorauswahl sollte leer sein

> Sollte mit [4415197](https://github.com/stadt-bielefeld/auik/commit/44151971429c0a4f08bee91d3365587f1db69f37) erledigt sein

Check

> > Objekte werden teilweise doppelt/dreifach angezeigt (Distinct?)
> > inaktive Objekte rausnehmen

> Mit [6fd2082](https://github.com/stadt-bielefeld/auik/commit/6fd208259cff2b06742657588e5cd347904506c4) sollten beide Punkte erledigt sein

Check

> > Für den Export fände ich es noch gut, wenn es dafür einen Button gibt.
>
> Grundsätzlich wäre das kein Problem, aber wäre dieser dann nicht doppelt vorhanden wenn mit #181 ein Exportbutton über die Abfrageauswahl reinkommt?

Doch, du hast vollkommen recht. 

> > wäre es möglich bei den Entwässerungsgebieten eine Mehrfachauswahl einzustellen? Oder mehr Sinn macht sogar die Kläranlageneinzugsgebiete zu nehmen: Heepen (1.01-1.05), Brake Ost (4.20-4-24), Brake West (4.00-4.19), AOL (5.28-5.31 und 7.32, 7.33.& 7.34), Sennestadt (8.35 & 8.36), Verl Sende (9.37)Heepen (1.01-1.05), Brake Ost (4.20-4-24), Brake West (4.00-4.19), AOL (5.28-5.31 und 7.32, 7.33.& 7.34), Sennestadt (8.35 & 8.36), Verl Sende (9.37)

 >Die zweite Variante wäre vermutlich die einfachere da Swing soweit ich weiß nicht sehr viel bietet um eine Mehrfachauswahl zu implementieren und wir da viel selbst bauen müssten. Für die zweite Variante könnte ich Elemente in der Combobox entsprechend ändern und die Abfrage anpassen, so dass die Id-Listen in den Klammern für die Filterung verwendet werden.

Gefällt mir auch eh besser

>>> unter Standort steht nur das Wort "Adresse" nicht aber die eigentliche Standortadresse
> 
> >Das Problem konnte ich bisher nicht reproduzieren. Könntest du nochmal schreiben wie du das Objekt erstellst das mit dem Wort "Adresse" in der Liste auftaucht?

Es ist bei allen Objekten so: In der Ergebniszeile steht "Adresse" anstatt " Hauptstraße 99, 99999 Dingsdorf" oder so

**Comment by Tilkiyim** [comment]
Hallo,

das mit den Entwässerungsgebieten ist super. Vielleicht kannst du mir einmal sagen wo ich finde wie die Daten in die Standortspalte kommen, also wo im Code ist das verankert? Habe gerade schon erfolglos gesucht. Vielleicht finde ich dann das Problem

**Comment by Tilkiyim** [comment]
hier komme ich leider  nicht weiter. 
In den Bereichen die du verlinkt hast werden die Daten für die Adresse nicht aufgerufen.

**Comment by awoestmann** [comment]
Mit 3832270055af11e9d7ef9bde03ca43e0e87f4a6e habe ich die Abfrage nochmal angepasst:
Anstatt der "basis.standort->bezeichnung" wir jetzt die komplette Adresse (Straße, Hausnr, Hausnrzusatz, Plz, Ort) aus der "basis.adresse" Tabelle zusammengesetzt.

**Comment by Tilkiyim** [comment]
Das passt, allerdings werden als Trenner %-Zeichen angezeigt, das ist nicht so gut lesbar.

**Comment by Tilkiyim** [comment]
Bei Objektart braucht es noch eine Auswahlmöglichkeit für "Alle Objektarten"

**Comment by awoestmann** [comment]
> Das passt, allerdings werden als Trenner %-Zeichen angezeigt, das ist nicht so gut lesbar.

Das Problem war hier noch das Handling von Adressen die nicht alle Teile enthalten haben. Mit 59b828ef22aa86a7133f9baf0266c9807f8ff26d sollten diese jetzt auch korrekt und ohne Trennerzeichen angezeigt werden.

> Bei Objektart braucht es noch eine Auswahlmöglichkeit für "Alle Objektarten"

Mit f980744093e78b746b2fbf59ae5b599364f05b73 enthält die Combobox jetzt auch ein leeres Element um alle Objektarten anzuzeigen.

**Comment by Tilkiyim** [comment]
passt. ich schließe hiermit diese Issue!
