### ISSUE TITLE
ELKA Bugs und Änderungswünsche

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#189]
**Bugs:**

- [x] Bei Betriebe, Anfallstellte, Einleitungsstelle, Messstelle funktioniert das Löschen der Datensätze nicht. 
- [x] Standorte: nur Adressen aus Bielefeld zulassen

**Änderungswünsche:**
- [x] Tabelleneinträge nach Importreihenfolge nummeriert werden, so können Fehler die in der Importdatei dokumentiert werden, zu dem Objekt zugeordnet werden.
- [x] Möglichkeit Einträge alphabetisch/nummerisch je nach Tabellenspalte  zu sortieren
- [x] Bei Ergebnistabelle „Adressen“ ID hinzufügen
- [x] Bei Ergebnistabelle „Standorte“ Hausnummer hinzufügen
- [x] Bei Ergebnistabelle „Betriebe“ Objekt-Id hinzufügen
- [x] Bei Ergebnistabelle „Abwasserbehandlungsanlage“ Adresse und Objekt-ID hinzufügen, Tabellenüberschrift  „Standort“ in Betreiber umbenennen
- [x] Bei Ergebnistabelle „Anfallstelle“ Adresse und Objekt ID hinzufügen, Tabellenüberschrift  „Standort“ in Betreiber umbenennen
- [x] #198
- [x] Bei Ergebnistabelle  „Messtelle“ Objekt ID, Betreiber und Adresse hinzufügen, Was ist Standort Nummer? 
- [ ] Ein „Delete All“ Button wäre super
- [x] Wenn der Import/Löschvorgang fertig ist,  soll die Importdatei automatisch geöffnet werden.
- [ ] Möglichkeit nur Verändere Daten übertragen (Update)

**Comment by Tilkiyim** [comment]
Getestet und funktioniert. Der restlichen Punkte können auch gerne umgesetzt werden. :)

**Comment by Tilkiyim** [comment]
mit "Delete all" war tatsächlich ein Button gemeint, alle Tabellen auf einmal zu löschen.

**Comment by awoestmann** [comment]
> Ich fände es gut, wenn die Reihenfolge der Tabellenspalten einheitlich ist, also solang vorhanden:
> 
> ID, Betreiber/Name, Adresse, und dann die Variablen

Mit fa1c06bc1ff335707e4074ee26d119a9e4545cba sollte die Reihenfolge jetzt einheitlich sein soweit die entsprechenden Spalten vorhanden sind.

> Fehler beim öffnen der Tabellen:
> 
>     * Messtelle
> 
>     * Betriebe
> 
> 
> Fehlermeldung hier: [Fehler.txt](https://github.com/stadt-bielefeld/auik/files/12454857/Fehler.txt)

Um die Objekt-IDs in der Tabelle anzuzeigen musste ich noch die ELKA-Views anpassen. Dazu habe ich ein entsprechendendes SQL-Skript in das `data/db`Verzeichnis gelegt:

https://github.com/stadt-bielefeld/auik/blob/4fce06786bce0e74366d4fa4fac979f022537d11/data/db/elka_updates.sql

Mit diesen Änderungen sollte der Fehler nicht mehr auftreten.

> mit "Delete all" war tatsächlich ein Button gemeint, alle Tabellen auf einmal zu löschen.

Mit 4fce06786bce0e74366d4fa4fac979f022537d11 habe ich die Funktion des Buttons prinzipiell schon einmal angepasst, konnte die Funktion aber bisher nur mit einem Dummy-Service testen

**Comment by Tilkiyim** [comment]
Was mir jetzt gerade so einfällt.
Durch die Ändeurgen die wir gerade vornehmen werden aber nicht die Daten geändert, die letztendlich nach ELKA übertragen werden oder? Denn die sind ja vorgegeben und können von uns nicht geändert werden. 
Die Änderungen sollen lediglich die Zuordbarkeit der einzelnen Objekte erleichtern.

**Comment by awoestmann** [comment]
> @awoestmann Was mir jetzt gerade so einfällt. Durch die Ändeurgen die wir gerade vornehmen werden aber nicht die Daten geändert, die letztendlich nach ELKA übertragen werden oder? Denn die sind ja vorgegeben und können von uns nicht geändert werden. Die Änderungen sollen lediglich die Zuordbarkeit der einzelnen Objekte erleichtern.

Grundsätzlich haben nur Änderungen an den elka_sync Models bzw. Mappings einen Einfluss auf die Daten die übertragen werden, da diese direkt in die Requests an die ELKA Schnittstellen gepackt werden. Dementsprechend werden neue Felder in diesen Mappings auch an ELKA gesendet, außer sie sind mit `@JsonIgnore` annotiert wie bspw. in EBetrieb:

https://github.com/stadt-bielefeld/auik/blob/83e3eaabac99a713e5315ee0cbd5a31ad6fff003/src/de/bielefeld/umweltamt/aui/mappings/elka_sync/EBetrieb.java#L57-L58

Die anderen Änderungen an der Tabellendarstellung sollten soweit keinen Einfluss auf die Übertragung haben da diese nur die TableModels betreffen und nicht die eigentlichen ELKA-Mappings.

Ansonsten ist während der Entwicklung aufgefallen, dass bei dem Voranstellen der Identifier an die Nr-Felder der Objekte einige Datentypen durcheinandergeworfen wurden. Damit konnte die Datenübertragung auf jeden Fall nicht mehr funktionieren (auch einige Zeit schon so wie es aussieht). Mit 83e3eaabac99a713e5315ee0cbd5a31ad6fff003 sollten die Probleme hoffentlich gelöst sein. Zumindest konnte ich damit jetzt endlich Daten an die Test-VM übertragen.

**Comment by Tilkiyim** [comment]
> > Ich fände es gut, wenn die Reihenfolge der Tabellenspalten einheitlich ist, also solang vorhanden:
> > ID, Betreiber/Name, Adresse, und dann die Variablen
> 
> Mit [fa1c06b](https://github.com/stadt-bielefeld/auik/commit/fa1c06bc1ff335707e4074ee26d119a9e4545cba) sollte die Reihenfolge jetzt einheitlich sein soweit die entsprechenden Spalten vorhanden sind.


- [ ] Bei Betriebe, Standorte, Abwasserbehandlungsanlage, Anfallstelle, Einleitungsstelle, messstelle ist die (Objekt-)ID noch ganz hinten- bitte sowie Id ganz vorne hinpacken. :) kann auch Statt Objekt ID überall ID heißen
- [ ] Bei Messstelle ist der Betreiber auch an der falschen stelle.
- [ ] Bei Standorte sollte Nr = id werden
- [ ] Id sollte so wie die anderen Spalten linksbündig sein

**Comment by awoestmann** [comment]
> Id sollte so wie die anderen Spalten linksbündig sein

Mit 90ce1cee9e1d7e3a496bd24c844a05df25b25e7b sollten Integer-Spalten jetzt auch linksbündig angezeigt werden

>  Bei Betriebe, Standorte, Abwasserbehandlungsanlage, Anfallstelle, Einleitungsstelle, messstelle ist die (Objekt-)ID noch ganz hinten- bitte sowie Id ganz vorne hinpacken. :) kann auch Statt Objekt ID überall ID heißen
> Bei Messstelle ist der Betreiber an der falschen Stelle + Standort Nr in Standort-Id umbenenen.
> Bei Standorte sollte Nr = id werden

Mit 04ca0ba4227977e674c72bbd3dc0748e91cce7cf sollten die Spalten jetzt alle an erster Stelle angezeigt werden und in "ID" umbenannt sein

**Comment by Tilkiyim** [comment]
Ich schließe das Issue und packe den Delete und Update-button in ein neues issue.
