### ISSUE TITLE
Maske Abfragemodule 

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#194]
Für die Anzeige der Abfragemodule soll eine neue Maske erstellt werden. Über ein Dropdown Menü sollen alle Abfragemodule geladen werden können (so wie beim Import). 
Folgende Auswertungen werden müssen hierbei nicht weiterhin auswählbar sein (können vielleicht auch einfach gelöscht werden)

- BasisAuswertung
- EinleiterAnfallstelleAuswertung
- EinleiterAnh50Auswertung
- EinleiterAnhang56Auswertung
- EinleiterGenehmigungAuswertung
- EinleiterPrioritätAuswertung
- EinleiterSuevkanAuswertung
- WiedervorlageAuswertung 

In der Maske soll es n och einen Button zum Export der Daten geben.

**Comment by awoestmann** [comment]
> Für die Anzeige der Abfragemodule soll eine neue Maske erstellt werden. Über ein Dropdown Menü sollen alle Abfragemodule geladen werden können (so wie beim Import).

> In der Maske soll es n och einen Button zum Export der Daten geben.

Die Funktionalität sollte mit c60a7107f6aafc105af0706f8166466e3de89d89 mit dem Modul "QueryChooser" soweit umgesetzt sein:

* Über ein Dropdown-Menü kann eine der vorhandenen Abfragen ausgewählt werden. Dabei wird das entsprechende Modul geladen
* Das Modul bietet einen Export der entsprechenden Ergebnistabelle an

> Folgende Auswertungen werden müssen hierbei nicht weiterhin auswählbar sein (können vielleicht auch einfach gelöscht werden) [...]

Mit 69b463baa75fd3bb130476ac2c8759c975bb520a habe ich die genannten Module entfernt. Die Module einfach nur auszublenden erscheint mir nicht zweckmäßig wenn diese ohnehin nicht mehr benötigt werden. Mit dem neuen Modul aus #186 sollten die Funktionen der gelöschten Module ja ohnehin ersetzt werden können.

**Comment by Tilkiyim** [comment]
Wäre es auch möglich die Buttons links doch zu lassen, da es nicht mehr so viele Abfragen sind finde ich es übersichtlicher als über das Dropdown (Sorry :D). Kann man dann den Exportierenbutton (besser "Tabelle speichern" ) vielleicht unterhalb der Ergebnistabelle möglich zu machen?

**Comment by awoestmann** [comment]
> Kann man dann den Exportierenbutton (besser "Tabelle speichern" ) vielleicht unterhalb der Ergebnistabelle möglich zu machen?

Mit b025cfa33f6ab8e9752ee2047952b994bef98633 habe ich den Button nach unten verschoben und den Text entsprechend angepasst.

> Wäre es auch möglich die Buttons links doch zu lassen, da es nicht mehr so viele Abfragen sind finde ich es übersichtlicher als über das Dropdown

Ich bin mir nicht sicher welche Buttons du jetzt meinst. Die links in der Navigation funktionieren ja noch wie gehabt wenn die entsprechenden Module in der Config aktiviert sind

**Comment by Tilkiyim** [comment]
Ich meine, dass man die unterschiedlichen Abfragen weiterhin über die Module links auswählt und nicht über das Dropdown was du erstellt hast. Dadurch, dass es deutlich weniger Abfragen als vorher Kategorie "Auswertung" sind, hätte man so schneller einen Überblick welche Abfragen es gibt. Daher müsste dann der Tabelle Speichern Button bei jeder Abfrage angelegt sein.

**Comment by awoestmann** [comment]
> Daher müsste dann der Tabelle Speichern Button bei jeder Abfrage angelegt sein.

Mit 921723028d04c3677959cfb4db65e95253365846 sollte jetzt in jedem Abfragemodul ein entsprechender Exportbutton vorhanden sein. 

> Ich meine, dass man die unterschiedlichen Abfragen weiterhin über die Module links auswählt und nicht über das Dropdown was du erstellt hast. Dadurch, dass es deutlich weniger Abfragen als vorher Kategorie "Auswertung" sind, hätte man so schneller einen Überblick welche Abfragen es gibt.

Der Punkt müsste doch eigentlich schon erledigt sein wenn man die Module wieder über die `auik.properties` einbindet. Oder fehlt hier noch etwas?

**Comment by Tilkiyim** [comment]
Ja, das passt :)
Dann kann das Modul "Abfragen" quasi wieder gelöscht werden. 
Sorry  :D 
Ich gebe das jetzt mal  zum testen in die Belegschaft, darum lasse ich das Issue mal noch offen.

**Comment by awoestmann** [comment]
> Dann kann das Modul "Abfragen" quasi wieder gelöscht werden.

Mit c616bc310ea63cad9bb3461a8d86d49c7c0cc139 ist das Modul jetzt gelöscht.

> Ich gebe das jetzt mal zum testen in die Belegschaft, darum lasse ich das Issue mal noch offen.

Dafür weise ich das Issue dann wieder dir zu.

**Comment by awoestmann** [comment]
Mit #199 habe ich schon mal einen PR für die Änderungen an den Abfragemodulen erstellt der dann gemerged werden kann sobald dieses Issue ebenfalls gelöst ist.

**Comment by Tilkiyim** [comment]
hab noch nen Typo korrigiert, dann darf aber gerne gemerged werden.  Kann halt sein, dass von meinen Kolleginnen noch was kommt. Bisher aber nichts zu mir durchgedrungen!
