### ISSUE TITLE
Maven Plugins - compile Jasperreports

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#195]
Funktioniert leider nicht mehr

**Comment by awoestmann** [comment]
Das Problem sollte mit ba8156e744c05957926d78a87798762921574844 ebenfalls gelöst sein. Siehe https://github.com/stadt-bielefeld/auik/issues/196#issuecomment-1689760729

**Comment by Tilkiyim** [comment]
Top! Läuft!
