### ISSUE TITLE
Maven Plugins Build

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#196]
Build wird nicht richtig durchgeführt: Dateiname nicht richtig und  wird nicht wie vorgehen an den richtigen Ort gespeichert.

**Comment by awoestmann** [comment]
Das Problem war hier tatsächlich recht simpel und umfasst auch das Problem in #195:

Die Plugins waren nur in einer `pluginManagement` Sektion in der pom definiert. Das bedeutet, dass sie zwar konfiguriert sind und auch in andere poms vererbt werden können, allerdings geschieht der eigentliche Aufruf in der `plugins` Sektion.

Mit  ba8156e habe ich die pom entsprechend angepasst, so dass die Plugins jetzt wieder aufgerufen werden sollten:

* Währen der compile Phase sollte das JasperReports Plugin wieder aufgerufen werden
* Mithilfe des git Plugins sollte die Versionsnummer wieder an den Dateinamen des Jars angehängt werden
* Mithilfe des antrun Plugins sollte die Jar-Datei wieder an den angegebenen Pfad kopiert werden

**Comment by Tilkiyim** [comment]
Top!Läuft!

**Comment by g-tom** [comment]
`mvn package` mit Apache Maven 3.6.3 unter Debian 11.8 erstellt `target/auik_prod-v1.3.0.jar` und meldet `BUILD SUCCESS`.

Unter welchen Bedingungen läuft's denn nicht?

**Comment by GerdGenuit** [comment]
Hast Du mal versucht, das Jar zu starten? Wieviel MB groß ist es denn? Bei uns läuft der Buildprozess auch durch, aber die Dependencies werden nicht dazu gepackt und damit startet es auch nicht.

**Comment by g-tom** [comment]
@GerdGenuit, könntest Du hier eine Schritt-für-Schritt-Anleitung teilen, mit der der Fehler reproduziert werden kann? Auch eine genaue Darstellung dessen, wie sich der Fehler für Euch darstellt wäre hilfreich.

**Comment by g-tom** [comment]
> Hast Du mal versucht, das Jar zu starten?

Ja, aber ich vermute `java -jar target/auik_prod-v1.3.0.jar` ist ohnehin nicht richtig.

> Wieviel MB groß ist es denn?

2,3

**Comment by GerdGenuit** [comment]
> > Hast Du mal versucht, das Jar zu starten?
> 
> Ja, aber ich vermute `java -jar target/auik_prod-v1.3.0.jar` ist ohnehin nicht richtig.

Doch, eigentlich müsste das Programm so starten
> 
> > Wieviel MB groß ist es denn?
> 
> 2,3

Das ist zu wenig. Mit den dependencies muss das jar über 80 MB groß sein.
