### ISSUE TITLE
Korrektur im Objekt Anfallstelle 

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#197]
In dem Objekt Anfallstelle, lässt sich die Bezeichnung nicht ändern. Wenn diese "überspreichert" wird ist beim näcshten öffnen wieder die Alte Bezeichnung da.

**Comment by awoestmann** [comment]
Hier war offenbar das Problem, dass die Anfallstelle Objekte in den Anhang-Panels erneut gespeichert wurden. Dabei konnten offenbar alte Daten erneut in die Datenbank geschrieben werden. Mit a1dfab944764f5a7ce58f21b5ebde3c4e0e793c4 sollte das Problem jetzt nicht mehr auftreten.
