### ISSUE TITLE
Adresse bei Anfallstelle, Abwasserbehandlungsanlage, Einleitungsstelle, Messstelle

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#198]

**Comment by Tilkiyim** [comment]
Hier ist bei der Adresse, lediglich die Adress ID angefügt. Hier müsste die Adresse analog der Lösung im #186 angepasst werden

**Comment by awoestmann** [comment]
Mit fa1c06bc1ff335707e4074ee26d119a9e4545cba habe ich die Darstellung der Adressen angepasst, so dass jetzt lesbare Strings in der Tabelle angezeigt werden.

**Comment by Tilkiyim** [comment]
Supi!
