### ISSUE TITLE
Verwendung Dependabot

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#27]
- Dependabot soll auf eigenem Branch automatisch ausgeführt werden
- Testumgebung  für Updates in den Abhängigkeiten
- Branch muss aktuell gehalten werden

**To Do:**
Anlegen Dependabot branch

**Comment by rrenkert** [comment]
Mit 9c6eb781538324d2ccf216e4239e3bee7943823f gibt es nun eine Konfiguration für dependabot. Damit ist dann der Ziel-Branch "dependabot-test". Der kann zum testen der aktualisierten Abhängigkeiten genutzt werden und bei bedarf dann in master zurück gemergt werden.

**Comment by Tilkiyim** [comment]
Der Branch ist eingerichtet und die Updates laufen.
