### ISSUE TITLE
bin-/lib-Ordner löschen

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#28]
Die beiden Ordner können & sollen gelöscht werden, da sie nicht benötigt werden.

**Comment by rrenkert** [comment]
Sollen wir die Ordner dann löschen und den commit machen, oder hast du den Stand bei dir noch vorliegen, so dass du das commiten kannst?

**Comment by Tilkiyim** [comment]
Macht ihr das lieber. ich weiß nicht, ob ich dann nicht doch wieder was comitte was dann nicht passt. Da ist das bei euch in sichereren Händen :)

**Comment by rrenkert** [comment]
Ist mit 70424517ad114f6f21841276993b0b64d7e51513 erledigt.
