### ISSUE TITLE
Fonts Jasperreports

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#35]
Beim Erstellen der Jasperreports aus der Programmierumgebung heraus sieht erstmal alles richtig und gut aus. 
Beim Starten der kompillierten jar ist das Drucken der PDFs auch möglich, jedoch werden die eigentlich **fettgedruckten** Abschnitte nicht in **fettgedruckt** dargestellt. 

Vermutung: Jasperversion in der komplillierten Version nicht mehr aktuell/passend zu der in der Entwicklungsumgebung.

Jasperversion bei mir: 6.13.0

**Comment by awoestmann** [comment]
Nach einem kurzen Test konnte ich das Problem reproduzieren:

* Wird die Anwendung bspw. über `mvn exec:java` gestartet werden alle Schriftarten in das pdf eingebettet. Die fettgedruckten Abschnitte werden dargestellt
* Wird die Anwendung über das erstelle jar gestartet werden die Schriftarten nicht in das pdf eingebettet und die fettgedruckten Abschnitte nicht dargestellt

Das jar enthält allerdings sowohl alle benötigten Schriftarten als auch die Jasper Font Extension. Ich werde mir das Problem nochmal weiter anschauen.

**Comment by awoestmann** [comment]
Das Problem scheint hier gewesen zu sein, dass beim Zusammenbau des Jars die Konfigurationsdateien von JasperReports überschrieben werden konnten.

Mit Commit 20e3a52 wird jetzt das Maven Shade Plugin für den Zusammenbau des Pakets verwendet, was das Problem beheben sollte. Die resultierende Jar-Datei hat in der aktuellen Plugin-Konfiguration den Dateinamen: `auik_prod_{version}.jar`, also bspw. `auik_prod_v1.1.0.jar`. Falls das noch geändert werden soll kann ich die Konfiguration noch entsprechend anpassen.

**Comment by Tilkiyim** [comment]
Da jetzt erstmal alles soweit läuft, schließe ich dieses Issue :)
