### ISSUE TITLE
Probleme mit Release-Action

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#36]
Da wir ( vor allem Gerd) gerade noch einige Bugfixes ausgebügelt haben, wollten wir ein neues release (v1.1.1) machen. 
Leider funktioniert der maven build nicht. Einen Re-Run habe ich auch ausprobiert, leider ergebnislos. 
Vielleicht hab ich auch was falsch gemacht. :) 

Ich danke für den Support.

**Comment by awoestmann** [comment]
Auf den ersten Blick scheint hier etwas mit den Dateinamen der Jars durcheinander geraten zu sein. Ich werde mir die pom.xml und die Konfiguration des Github Workflows noch einmal anschauen

**Comment by awoestmann** [comment]
Mit Commit 32c4708 habe ich die tag.yml angepasst, so dass das Problem mit den Dateinamen jetzt gelöst sein sollte.

Den v1.1.1-Tag habe ich auch noch auf den Commit ungebogen. Der Release-Workflow ist damit jetzt auch Problemlos durchgelaufen und hat einen neuen Release-Draft erstellt.

**Comment by Tilkiyim** [comment]
Wunderbar. Das klappt ja gut hier mit den Zuständigkeiten. :)  

@GerdGenuit muss das Schema noch angepasst werden für den Release oder kann ich da das v.1.1.0 reinpacken?

**Comment by GerdGenuit** [comment]
An dem Schema hat sich von 1.1.0 auf 1.1.1 nichts geändert. Einem Release steht meiner Meinung nach nichts im Wege.

**Comment by Tilkiyim** [comment]
So jetzt brauche ich  nochmal Hilfe beim Release. Durch das Problem beim Erstellen des Relases gibt es gerade zwei Versionen mit der Bennenung v1.1.1 das von mir publizierte ist das falsche, das muss weg. Kann mir da jemand helfen?

**Comment by Tilkiyim** [comment]
Danke :) Habe den Release jetzt veröffentlicht und schließe damit das Issue.
