### ISSUE TITLE
Actions Java CI funktioniert nicht

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#38]
Weder bei meinen noch bei Alex's letzten Commits ist die Java CI druchgelaufen. Fehler Code ist bei allen der gleiche: Could not resolve dependencies (maven). 
Habt ihr ne Idee?

**Comment by rrenkert** [comment]
Das ist nun behoben. Seit kurzem besteht Maven auf https für zusätzliche Repositories.

Dies sind die relevanten commits:
5cffdd7c2ab562cec01170a374c0f6af9599d673
dba2650f9b7871bc77be718c8306c1f64503c02e
25e029e96738305e116042760a8aae6f316a8844
