### ISSUE TITLE
ToDo- Import Sielhautergebnisse - Zirkonium

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#53]
Wenn in den Importtabelle der Parameter Zirkonium dabei ist, wird der Import abgebrochen. Alle Parameter bis zu dem ersten Zirkonium werden jedoch trotzdem importiert. Fehlermeldung sagt lediglich, dass der Import fehlgeschlagen ist. 

Bei anderen, nicht zu importierenden Sonderparametern wird der Import dieser einfach übersprungen. Das sollte für Zirkonium auch genau so gehandhabt werden. 

Angehängt eine Testdatei für den Sielhautimport.

[ASCII_SIELHAUT_BIELEFELD_K-2211086.csv](https://github.com/stadt-bielefeld/auik/files/9645606/ASCII_SIELHAUT_BIELEFELD_K-2211086.csv)

**Comment by Tilkiyim** [comment]
HAb hier noch ne verkürzte Variante der Importdatei mit Zirkonium und Kohlenwasserstoffen (Beides "Sonderparameter")

[Testimport.csv](https://github.com/stadt-bielefeld/auik/files/9706976/Testimport.csv)

**Comment by awoestmann** [comment]
Dieses Issue sollte mit #76 gelöst sein
