### ISSUE TITLE
ToDo- Speichern von allen Tabs 

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#55]
Bei allen Objekten sollte es so sein, dass egal in welchem Tab man sich gerade befindet, Änderungen in allen Tabs gespeichert werden. Bei Verlassen der Seite, wenn etwas nicht gespeichert, sollte nachgefragt werden, ob die Änderungen beibehalten werden sollen.

**Comment by awoestmann** [comment]
Dieses Issue sollte mit #106 gelöst sein
