### ISSUE TITLE
To Do - Auswertungen -Abfragen

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#58]
1. Sachbearbeiter sollen selber einstellen können welche Auswertungen bei Ihnen erscheinen.
2.  Auswertungen alle Objekte pro Sachbearbeiter anzeigen
3.  Auswertungen einzelne Objektarten
4. Auswertung einzelne Objektarten pro Sachbearbeiter (1 und 2)  (Vielleicht ist 2-4 auch über eine Auswertung mit verschiedenen Parametern machbar) 
5. In allen Auswertungen: Betreiber, Standort, Entwässerungsgebiet, Sachbearbeiter 1, Sachbearbeiter 2, 
6. AUswertungen BWK -BHKW & ABA funktionieren nicht
7. Auswertung Anhang 49 - hier werden auch Fettabscheider mit aufgelistet - die müssen raus

**Comment by awoestmann** [comment]
Wenn ich das richtig sehe dürften mit den Issues #181, #182, #184, #185 und #186 einige dieser Punkte schon abgedeckt sein.
@Tilkiyim Vermutlich wäre es sinnvoll die Liste noch einmal zu aktualisieren bevor man sich das Issue weiter anschaut

**Comment by Tilkiyim** [comment]
@awoestman 
Für die fehlenden Überarbeitungschritte öffne ich ein neues Issue.
