### ISSUE TITLE
To Do- Zusammenfassung Import

### ISSUE THREAD

**Issue by Tilkiyim** [stadt-bielefeld/auik#77]
Die beiden Importvarianten "Sielhaut" und "Abwasser" sollen in einem Fenster auftauchen. Das Modul Sielhautimport soll zum Labor - Import hinzugefügt werden. Über eine Auswahl "Sielhaut" oder " Abwasser" soll in einem 1. Schritt zwischen den beiden Importvarianten differenziert werden

Wie bei dem Sielhautimport hier iene Rückmeldung über importierte Datensätze
[22-08-03 E178.csv](https://github.com/stadt-bielefeld/auik/files/9723492/22-08-03.E178.csv)

**Comment by awoestmann** [comment]
Dieses Issue sollte mit #105 gelöst sein, daher schließe ich hier
