### ISSUE TITLE
Datenbankschema initialisieren

### ISSUE THREAD

**Issue by jdugge** [stadt-bielefeld/auik#9]
Wir versuchen, AUIK bei uns zum Laufen zu bringen, scheitern aber momentan wohl noch am Datenbankschema.

Das Kompilieren mit Maven hat problemlos geklappt und die Runtime lässt sich ausführen. Es öffnet sich eine Login-Maske. Nach Eingabe einer gültigen Nutzername/Passwort-Kombination für den lokal laufenden Postgresql-Server erscheint nach kurzer Zeit die Fehlermeldung "Der eingebene Benutzername oder das Passwort war falsch (oder es ist aus anderen Gründen keine Verbindung mit der Datenbank möglich), bitte versuchen Sie es erneut!". In der Konsole findet sich folgende Fehlermeldung `org.postgresql.util.PSQLException: FATAL: database "fisumwelt" does not exist`.

Nach Anlage einer neuen leeren Datenbank mit dem Namen `fisumwelt` und erneutem Start von AUIK erhalten wir nun folgende Fehlermeldung in der Konsole: `ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] - ERROR: relation "basis.adresse" does not exist`. Es scheint, als müssten wir also erst noch das Datenbankschema anlegen. Liegen wir mit der Analyse richtig? Gibt es zum Initialisieren der Datenbank ein Skript oder eine Vorlage?

**Comment by GerdGenuit** [comment]
Hallo,

vielen Dank für Ihr Interesse an unserem AUIK. Das SQL-Skript zum Erzeugen einer (fast) leeren Datenbank habe ich beigefügt. Es enthält ein paar notwendige Daten, damit die Oberfläche starten kann, aber nichts, womit man arbeiten könnte. An einem Demodatensatz arbeiten wir noch, haben aber gerade wesentliche Änderungen am Schema durchgeführt, sodass die Fertigstellung noch etwas dauern kann.

Genauso sieht es mit dem Handbuch aus. Auch das ist auch noch nicht fertig, der derzeitige Stand kann aber für den Einstieg schon mal einen ganz guten Einblick in das Programm bieten.

Viel Spaß beim Testen.

Mit freundlichen Grüßen
Gerhard Genuit


Von: Jürnjakob Dugge <notifications@github.com>
Gesendet: Dienstag, 2. Juni 2020 21:20
An: stadt-bielefeld/auik <auik@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [stadt-bielefeld/auik] Datenbankschema initialisieren (#9)


Wir versuchen, AUIK bei uns zum Laufen zu bringen, scheitern aber momentan wohl noch am Datenbankschema.

Das Kompilieren mit Maven hat problemlos geklappt und die Runtime lässt sich ausführen. Es öffnet sich eine Login-Maske. Nach Eingabe einer gültigen Nutzername/Passwort-Kombination für den lokal laufenden Postgresql-Server erscheint nach kurzer Zeit die Fehlermeldung "Der eingebene Benutzername oder das Passwort war falsch (oder es ist aus anderen Gründen keine Verbindung mit der Datenbank möglich), bitte versuchen Sie es erneut!". In der Konsole findet sich folgende Fehlermeldung org.postgresql.util.PSQLException: FATAL: database "fisumwelt" does not exist.

Nach Anlage einer neuen leeren Datenbank mit dem Namen fisumwelt und erneutem Start von AUIK erhalten wir nun folgende Fehlermeldung in der Konsole: ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] - ERROR: relation "basis.adresse" does not exist. Es scheint, als müssten wir also erst noch das Datenbankschema anlegen. Liegen wir mit der Analyse richtig? Gibt es zum Initialisieren der Datenbank ein Skript oder eine Vorlage?

**Comment by BjoernSchilberg** [comment]
Moin, @GerdGenuit ,
gibt es hier noch etwas zu klären oder zu tun? Oder kann der Issue geschlossen werden?
